name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Build and Test
      run: |
        go build -v
        go test -v ./...

    # I comment these commands below since I will not maintain docker and kube envi permanently
    #- name: Build Docker Image
    #  uses: docker/build-push-action@v4
    #  with:
    #    context: .
    #    push: true
    #    tags: pauluswi/kiel:latest

    #- name: Deploy to Kubernetes
    #  uses: azure/k8s-deploy@v4
    #  with:
    #    manifests: |
    #      k8s/deployment.yaml
    #      k8s/service.yaml
    #    images: pauluswi/kiel:latest
